In [4]:
import pandas as pd    # Import pandas library
import numpy as np

In [5]:
df = pd.read_csv("day_1.csv")      # To read file and import

print(df.head(5))
print(df.isnull().sum())        # Check for null rows

   order_id     product_id  region  revenue  order_date
0         1    Food - Meat  Bengal     1759  2025-06-07
1         2  Food - Grains  Kerala     1184  2025-10-25
2         3           Home  Punjab     1276  2025-10-05
3         4           Toys  Bengal     1782  2025-09-22
4         5   Food - Dairy  Bengal     1578  2025-10-13
order_id      0
product_id    0
region        0
revenue       0
order_date    0
dtype: int64

In [6]:
Total_revenue = df["revenue"].sum()
print("Total revenue of all products is" , Total_revenue)  # Total Revenue

Total revenue of all products is 150994

In [7]:
df.groupby("region")["revenue"].sum()       # Total revenue after dividing it by Regions

region
Assam                4385
Bengal              22545
Gujarat             19027
Himachal Pradesh    11142
Kashmir             21133
Kerala              13894
Odisha              15961
Punjab              12602
Rajasthan           21426
Telangana            8879
Name: revenue, dtype: int64

In [13]:
#  Order Count per Region
df.groupby("region")["revenue"].count() 

# Average Revenue per Order

df.groupby("region")["revenue"].mean().reset_index().round(2)

             region  revenue
0             Assam  1461.67
1            Bengal  1610.36
2           Gujarat  1463.62
3  Himachal Pradesh  1591.71
4           Kashmir  1625.62
5            Kerala  1543.78
6            Odisha  1596.10
7            Punjab  1400.22
8         Rajasthan  1428.40
9         Telangana  1268.43

In [15]:
df.groupby("region")["revenue"].agg(["count", "mean"]).reset_index().round(2)

             region  count     mean
0             Assam      3  1461.67
1            Bengal     14  1610.36
2           Gujarat     13  1463.62
3  Himachal Pradesh      7  1591.71
4           Kashmir     13  1625.62
5            Kerala      9  1543.78
6            Odisha     10  1596.10
7            Punjab      9  1400.22
8         Rajasthan     15  1428.40
9         Telangana      7  1268.43